env:
- name: DEV
  value: "true"


grases:
  - name: gras
    enabled: true
    gras: {}
    grapi:
      ssl: false
      dev: true
    gruim:
      ssl: false
      dev: true


ingress:
  enabled: true
  hosts:
    - host: myapp.test
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
